[build]
   command: "next build"
  publish: "out"
  functions: "out/functions"
  output: "export"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
